# Generated by Django 5.1.4 on 2025-03-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_rename_id_admin_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id',
            new_name='id_admin',
        ),
    ]
