# Generated by Django 5.1.4 on 2025-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_maestro_apellido_materno_maestro_apellido_paterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='contrasenaTemporal',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
