# Generated by Django 5.1.4 on 2025-03-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rename_nombre_rol_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='id_rol',
            new_name='id',
        ),
    ]
