# Generated by Django 5.1.5 on 2025-03-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado_id', models.IntegerField()),
                ('estado_asistencia', models.CharField(blank=True, max_length=1, null=True)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clase.clase')),
            ],
        ),
    ]
