# Generated by Django 5.1.5 on 2025-03-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='alumno_id',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='clase_id',
            new_name='clase',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='estado_asistencia',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.estadoasistencia'),
        ),
    ]
