# Generated by Django 5.1.5 on 2025-04-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_estado_delete_estadoasistencia'),
        ('unidad', '0004_unidad_fecha_fin_unidad_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad'),
        ),
    ]
