# Generated by Django 5.2 on 2025-04-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='carrera_id',
            new_name='carrera',
        ),
    ]
