# Generated by Django 5.1.4 on 2025-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(max_length=2),
        ),
    ]
