# Generated by Django 5.1.4 on 2025-03-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_grado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='id_alumno',
            new_name='id',
        ),
    ]
