# Generated by Django 5.1.4 on 2025-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_apellido_materno_alumno_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contrasenaTemporal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
