# Generated by Django 5.1.4 on 2025-04-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_contrasenatemporal_alter_alumno_grado'),
        ('grupo', '0003_grupo_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='grupo.grupo'),
        ),
    ]
