# Generated by Django 5.1.4 on 2025-04-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
        ('maestros', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
                ('dia_clase', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo')),
                ('maestro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.maestro')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
            ],
        ),
    ]
