# Generated by Django 5.1.4 on 2025-03-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='materia.materia')),
            ],
        ),
    ]
