# Generated by Django 5.1.4 on 2025-03-24 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
