# Generated by Django 5.1.5 on 2025-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0003_remove_unidad_fecha_fin_remove_unidad_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
