# Generated by Django 5.1.4 on 2025-03-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='id_grupo',
            new_name='id',
        ),
    ]
