# Generated by Django 5.2 on 2025-04-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='carrera.carrera'),
        ),
    ]
