# Generated by Django 5.1.4 on 2025-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_rename_id_grupo_grupo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grado',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
